/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/users/{employeeId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                employeeId: string;
            };
            cookie?: never;
        };
        /**
         * ユーザー詳細取得
         * @description 指定した社員番号の詳細情報を返す。
         */
        get: operations["getUserDetail"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * ユーザー一覧取得
         * @description 全社員の情報を配列で返す。
         */
        get: operations["getUsers"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * @description 所属グループ
         * @enum {string}
         */
        UserGroup: "エンジニア" | "経理" | "営業";
        /**
         * @description 評価ランク（A が最高）
         * @enum {string}
         */
        UserRating: "A" | "B" | "C" | "D";
        DepartmentHistory: {
            /** @description 部署名 */
            department: string;
            /**
             * @description 着任年月（YYYY-MM）
             * @example 2018-04
             */
            from: string;
            /**
             * @description 離任年月（YYYY-MM）。null は現在在籍
             * @example 2021-03
             */
            to: string | null;
        };
        UserDetail: {
            /** @description 社員番号 */
            employeeId: string;
            /** @description 氏名 */
            name: string;
            /**
             * Format: date
             * @description 生年月日（YYYY-MM-DD）
             * @example 1990-05-15
             */
            dateOfBirth: string;
            /** @description 月給（円） */
            salary: number;
            rating: components["schemas"]["UserRating"];
            /** @description 部署経歴（古い順） */
            departmentHistory: components["schemas"]["DepartmentHistory"][];
            group: components["schemas"]["UserGroup"];
        };
        GetUserDetailResponse: components["schemas"]["UserDetail"];
        User: {
            /**
             * @description 社員番号
             * @example E-1001
             */
            employeeId: string;
            /**
             * @description 氏名
             * @example 山田 太郎
             */
            name: string;
            /**
             * @description 年齢
             * @example 34
             */
            age: number;
            /**
             * @description 住所
             * @example 東京都渋谷区本町1-2-3
             */
            address: string;
            group: components["schemas"]["UserGroup"];
            /**
             * Format: date
             * @description 雇用年月日（YYYY-MM-DD）
             * @example 2018-04-01
             */
            hireDate: string;
            /**
             * @description 連絡先（電話番号）
             * @example 090-1111-2222
             */
            phone: string;
            /**
             * @description 備考
             * @example フロントエンド担当
             */
            note: string;
        };
        GetUsersResponse: {
            users: components["schemas"]["User"][];
        };
        ErrorResponse: {
            /**
             * @description エラーメッセージ
             * @example Internal Server Error
             */
            message: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getUserDetail: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                employeeId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 取得成功 */
            200: {
                headers: { [name: string]: unknown };
                content: {
                    "application/json": components["schemas"]["GetUserDetailResponse"];
                };
            };
            /** @description 該当ユーザーが存在しない */
            404: {
                headers: { [name: string]: unknown };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description サーバーエラー */
            500: {
                headers: { [name: string]: unknown };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    getUsers: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 取得成功 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "users": [
                     *         {
                     *           "employeeId": "E-1001",
                     *           "name": "山田 太郎",
                     *           "age": 34,
                     *           "address": "東京都渋谷区本町1-2-3",
                     *           "group": "エンジニア",
                     *           "hireDate": "2018-04-01",
                     *           "phone": "090-1111-2222",
                     *           "note": "フロントエンド担当"
                     *         }
                     *       ]
                     *     }
                     */
                    "application/json": components["schemas"]["GetUsersResponse"];
                };
            };
            /** @description サーバーエラー */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
}
